@baseUrl = http://localhost:5000

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "123456"
}

###
