version: '3.8'

services:
  postgres:
    container_name: nest-clean-arch-pg
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean-arch
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres